paths:
  /products:
    get:
      description: Fetch all the products
      tags:
        - Product Management
      operationId: fetchAllProducts
      responses:
        "200":
          description: success fetchAllProducts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    post:
      description: Create product of the application
      tags:
        - Product Management
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: User creation successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"

  /products/{productId}:
    parameters:
      - $ref: "#/components/parameters/productId"
    get:
      description: get details of the product
      tags:
        - Product Management
      operationId: getProductDetails
      responses:
        "200":
          description: product details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
    post:
      description: update details of the product
      tags:
        - Product Management
      operationId: updateProductDetails
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: productId of the product to be fetched
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: successfully updated product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"
    delete:
      description: remove product
      tags:
        - Product Categories Management
      operationId: removeProduct
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: productId of the product to be fetched
      responses:
        "200":
          description: deleted products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"
  /categories:
    get:
      description: Fetch all categories
      tags:
        - Product Categories Management
      operationId: fetchCategories
      responses:
        "200":
          description: List of all categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
    post:
      description: create new Category
      tags:
        - Product Categories Management
      operationId: createCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        "201":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"

  /categories/{code}:
    parameters:
      - $ref: "#/components/parameters/productCode"
    get:
      description: Fetch all categories
      tags:
        - Product Categories Management
      operationId: getCategory
      responses:
        "200":
          description: List of all categories
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
    post:
      description: create new Category
      tags:
        - Product Categories Management
      operationId: updateCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        "201":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"
    delete:
      description: delete the selected Category
      tags:
        - Product Categories Management
      operationId: removeCategory
      responses:
        "200":
          description: successful deletion
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"

components:
  parameters:
    productCode:
      in: path
      name: code
      required: true
      schema:
        type: string
      description: code of the category to be deleted
    productId:
      in: path
      name: productId
      required: true
      schema:
        type: string
      description: productId of the product to be fetched
  schemas:
    Category:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        description:
          type: string
        products:
          type: array
          items:
            type: string

    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        categories:
          type: array
          items:
            type: string
        description:
          type: string
        tag:
          type: array
          items:
            type: string
        price:
          type: number
        currency:
          type: string
        restrictions:
          type: object
          properties:
            maximum:
              type: number
            minimun:
              type: number
            description:
              type: string
        images:
          type: array
          items:
            type: string
        campaigns:
          type: array
          items:
            type: string
