paths:
  /roles:
    get:
      description: Fetch all the roles
      operationId: getAllRoles
      responses:
        "200":
          description: All the roles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Role"
    post:
      description: Create role for an user
      operationId: createRole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Role"
      responses:
        "201":
          description: User creation successful
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                properties:
                  status:
                    type: string

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        description:
          type: string

    Role:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
        description:
          type: string
