paths:
  /user:
    post:
      description: Create user of the application
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDetails"
      responses:
        "201":
          description: User creation successful
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                properties:
                  status:
                    type: string

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        description:
          type: string

    UserDetails:
      type: object
      required:
        - identifier
        - password
      properties:
        identifier:
          type: object
          properties:
            username:
              type: string
            firstName:
              type: string
            lastName:
              type: string
            email:
              type: string
            mobileNumber:
              type: string
        password:
          type: string
        role:
          type: array
          items:
            type: string

    Role:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
        description:
          type: string
